In [1]:
#Step 1 : Import Libraries
import pandas as pd

In [2]:
#Step 2 : Read / Load data
df = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Salary%20Data.csv')

In [3]:
df.head() #returns first 5 rows

   Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [4]:
df.info() #shows information about file

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Experience Years  40 non-null     float64
 1   Salary            40 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 772.0 bytes

In [5]:
df.describe() #shows summary statistics

       Experience Years         Salary
count         40.000000      40.000000
mean           5.152500   74743.625000
std            2.663715   25947.122885
min            1.100000   37731.000000
25%            3.200000   56878.250000
50%            4.600000   64472.500000
75%            6.875000   95023.250000
max           10.500000  122391.000000

In [6]:
#Step 3 : Define y(output) and x(input)
df.columns

Index(['Experience Years', 'Salary'], dtype='object')

In [7]:
y = df['Salary']
x = df[['Experience Years']]

In [8]:
y

0      39343
1      42774
2      46205
3      37731
4      43525
5      39891
6      48266
7      56642
8      60150
9      54445
10     64445
11     60000
12     57189
13     60200
14     63218
15     55794
16     56957
17     57081
18     59095
19     61111
20     64500
21     67938
22     66029
23     83088
24     82200
25     81363
26     93940
27     91000
28     90000
29     91738
30     98273
31    101302
32    113812
33    111620
34    109431
35    105582
36    116969
37    112635
38    122391
39    121872
Name: Salary, dtype: int64

In [9]:
x

    Experience Years
0                1.1
1                1.2
2                1.3
3                1.5
4                2.0
5                2.2
6                2.5
7                2.9
8                3.0
9                3.2
10               3.2
11               3.5
12               3.7
13               3.8
14               3.9
15               4.0
16               4.0
17               4.1
18               4.3
19               4.5
20               4.7
21               4.9
22               5.1
23               5.3
24               5.5
25               5.9
26               6.0
27               6.2
28               6.5
29               6.8
30               7.1
31               7.9
32               8.2
33               8.5
34               8.7
35               9.0
36               9.5
37               9.6
38              10.3
39              10.5

In [10]:
#Step 4 : Train Test split
from sklearn.model_selection import train_test_split

In [11]:
x_train , x_test , y_train , y_test = train_test_split(x , y , random_state = 2529)

In [12]:
x.shape , x_train.shape , x_test.shape

((40, 1), (30, 1), (10, 1))

In [13]:
y.shape , y_train.shape , y_test.shape

((40,), (30,), (10,))

In [14]:
#Step 5 : Select a model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [15]:
#Step 6 : Train model
model.fit(x_train , y_train)

LinearRegression()

In [16]:
model.intercept_

np.float64(27010.963630394683)

In [17]:
model.coef_

array([9343.3671387])

In [18]:
#Step 7 : Prediction
y_pred = model.predict(x_test)

In [19]:
#Step 8 : Evaluate Performance
from sklearn.metrics import mean_absolute_percentage_error

In [20]:
mean_absolute_percentage_error(y_test , y_pred)

0.06230870755908321